services:
  barracuda-description:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    user: root
    privileged: true
    image: barracuda-description
    container_name: barracuda-description
    tty: true
    network_mode: host
    ipc: host
    volumes:
      - ${HOME}/.ssh:/root/.ssh
  barracuda-jetson-dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    user: root
    privileged: true
    image: barracuda-description-dev
    container_name: barracuda-description-dev
    tty: true
    network_mode: host
    ipc: host
    volumes:
      - ${HOME}/.ssh:/root/.ssh
      - ${HOME}/.gitconfig:/root/.gitconfig
      - ${HOME}/.vimrc:/root/.vimrc
      - ../barracuda_description:/ros2_ws/src/barracuda_description
    profiles: ["dev"]
